const pool = require("../config/db");
const {
    addCvVersion,
    assertCvNotUsedByOpenParticipation,
    getCvVersions,
    getCvVersionById,
    getLatestCvVersion,
    getLatestCvVersionForParticipation,
    getStudentCv
} = require("../utils/cvVersions");
const { assertCompanyCanAccessEvent } = require("../utils/eventAccess");
const { deleteFileIfExists, sendCvVersionFile: streamCvVersionFile } = require("../utils/cvFiles");
const { HttpError, isHttpError } = require("../utils/httpError");

function handleControllerError(res, err) {
    if (isHttpError(err))
        return res.status(err.status).json({ error: err.message, code: err.code });

    res.status(500).json({ error: err.message });
}

function mapCvResponse(cv, versions) {
    const latestVersion = versions[0] || null;

    return {
        id: cv.id,
        student_id: cv.student_id,
        created_at: cv.created_at,
        updated_at: cv.updated_at,
        latest_version: latestVersion,
        versions,

        // Temporary compatibility fields for the current frontend.
        file_path: latestVersion?.file_path || null,
        original_name: latestVersion?.original_name || null,
        uploaded_at: latestVersion?.uploaded_at || null
    };
}

async function removeUploadedFileOnFailure(req) {
    if (!req.file)
        return;

    try {
        await deleteFileIfExists(req.file.filename);
    } catch {
        // Preserve the original request error; cleanup failure is secondary here.
    }
}

async function getParticipationForFileAccess(participationId) {
    const [rows] = await pool.query(
        `SELECT
            participations.id,
            participations.student_id,
            participations.event_id,
            participations.selected_cv_id
         FROM participations
         WHERE participations.id = ?
         LIMIT 1`,
        [participationId]
    );

    return rows[0] || null;
}

async function assertCompanyScannedParticipation(companyId, participationId) {
    const [rows] = await pool.query(
        `SELECT id
         FROM scan_logs
         WHERE company_id = ?
         AND participation_id = ?
         LIMIT 1`,
        [companyId, participationId]
    );

    if (rows.length === 0)
        throw new HttpError(403, "Company has not scanned this participation", "SCAN_REQUIRED");
}

async function assertCanAccessCvVersion(user, cvVersion) {
    if (user.role === "admin")
        return;

    if (user.role === "student" && cvVersion.student_id === user.id)
        return;

    throw new HttpError(403, "Forbidden", "CV_VERSION_FORBIDDEN");
}

async function assertCanAccessParticipationCv(user, participation) {
    if (user.role === "admin")
        return;

    if (user.role === "student" && participation.student_id === user.id)
        return;

    if (user.role === "company") {
        await assertCompanyCanAccessEvent(user.id, participation.event_id);
        await assertCompanyScannedParticipation(user.id, participation.id);
        return;
    }

    throw new HttpError(403, "Forbidden", "PARTICIPATION_CV_FORBIDDEN");
}

// POST /cv/upload
// Uploads the student's first CV file, or appends a new retained CV version.
// QR codes are generated by the participation flow, not by CV upload.
exports.uploadCV = async (req, res) => {
    try {
        const studentId = req.user.id;
        const { cv, version } = await addCvVersion(studentId, req.file);
        const versions = await getCvVersions(cv.id);

        res.json({
            message: "CV version uploaded",
            cv: mapCvResponse(cv, versions),
            version
        });

    } catch (err) {
        await removeUploadedFileOnFailure(req);
        handleControllerError(res, err);
    }
};

// GET /cv/me
// Returns the student's logical CV, latest version, and retained version list.
exports.getMyCV = async (req, res) => {
    try {
        const studentId = req.user.id;
        const cv = await getStudentCv(studentId);

        if (!cv)
            return res.status(404).json({ error: "No CV found" });

        const versions = await getCvVersions(cv.id);

        if (versions.length === 0)
            return res.status(404).json({ error: "No CV versions found" });

        res.json(mapCvResponse(cv, versions));

    } catch (err) {
        handleControllerError(res, err);
    }
};

// PUT /cv
// Appends a new retained version to the student's existing logical CV.
// The participation QR remains stable because it resolves to the latest version.
exports.replaceCV = async (req, res) => {
    try {
        const studentId = req.user.id;
        const existingCv = await getStudentCv(studentId);

        if (!existingCv)
            return res.status(404).json({ error: "No CV to replace" });

        const { cv, version } = await addCvVersion(studentId, req.file);
        const versions = await getCvVersions(cv.id);

        res.json({
            message: "CV version uploaded",
            cv: mapCvResponse(cv, versions),
            version
        });

    } catch (err) {
        await removeUploadedFileOnFailure(req);
        handleControllerError(res, err);
    }
};

// DELETE /cv
// Deletes the student's logical CV and retained files unless it is selected by
// an open participation. Closed participations are detached first so historical
// event records remain without keeping a hard dependency on the CV.
exports.deleteCV = async (req, res) => {
    const connection = await pool.getConnection();

    try {
        const studentId = req.user.id;
        const cv = await getStudentCv(studentId, connection);

        if (!cv)
            return res.status(404).json({ error: "No CV found" });

        await assertCvNotUsedByOpenParticipation(cv.id, connection);

        const latestVersion = await getLatestCvVersion(cv.id, connection);
        const versions = await getCvVersions(cv.id, connection);

        await connection.beginTransaction();

        await connection.query(
            `UPDATE participations
             JOIN events ON events.id = participations.event_id
             SET participations.selected_cv_id = NULL
             WHERE participations.selected_cv_id = ?
             AND NOT (
                events.status = 'open'
                AND events.closed_at IS NULL
             )`,
            [cv.id]
        );

        await connection.query(
            "DELETE FROM cvs WHERE id = ? AND student_id = ?",
            [cv.id, studentId]
        );

        await connection.commit();

        for (const version of versions) {
            await deleteFileIfExists(version.file_path);
        }

        res.json({
            message: "CV deleted",
            deleted_latest_version: latestVersion || null
        });

    } catch (err) {
        await connection.rollback();
        handleControllerError(res, err);
    } finally {
        connection.release();
    }
};

// GET /cv/version/:versionId/file
// Streams a specific retained CV version for the owning student or any admin.
exports.sendCvVersionFile = async (req, res) => {
    try {
        const cvVersion = await getCvVersionById(req.params.versionId);

        if (!cvVersion)
            return res.status(404).json({ error: "CV version not found" });

        await assertCanAccessCvVersion(req.user, cvVersion);

        return streamCvVersionFile(res, cvVersion);

    } catch (err) {
        handleControllerError(res, err);
    }
};

// GET /cv/participation/:participationId/file
// Streams the latest CV version selected for a participation. Companies must
// have scanned the participation and still be assigned to an active event.
exports.sendParticipationCvFile = async (req, res) => {
    try {
        const participation = await getParticipationForFileAccess(req.params.participationId);

        if (!participation)
            return res.status(404).json({ error: "Participation not found" });

        if (!participation.selected_cv_id)
            return res.status(404).json({ error: "Participation has no selected CV" });

        await assertCanAccessParticipationCv(req.user, participation);

        const cvVersion = await getLatestCvVersionForParticipation(participation.id);

        if (!cvVersion)
            return res.status(404).json({ error: "CV version not found" });

        return streamCvVersionFile(res, cvVersion);

    } catch (err) {
        handleControllerError(res, err);
    }
};
