const pool = require("../config/db");
const {
    addCvVersion,
    assertCvNotUsedByOpenParticipation,
    getCvVersions,
    getLatestCvVersion,
    getStudentCv
} = require("../utils/cvVersions");
const { deleteFileIfExists } = require("../utils/cvFiles");
const { isHttpError } = require("../utils/httpError");

function handleControllerError(res, err) {
    if (isHttpError(err))
        return res.status(err.status).json({ error: err.message, code: err.code });

    res.status(500).json({ error: err.message });
}

function mapCvResponse(cv, versions) {
    const latestVersion = versions[0] || null;

    return {
        id: cv.id,
        student_id: cv.student_id,
        created_at: cv.created_at,
        updated_at: cv.updated_at,
        latest_version: latestVersion,
        versions,

        // Temporary compatibility fields for the current frontend.
        file_path: latestVersion?.file_path || null,
        original_name: latestVersion?.original_name || null,
        uploaded_at: latestVersion?.uploaded_at || null
    };
}

async function removeUploadedFileOnFailure(req) {
    if (!req.file)
        return;

    try {
        await deleteFileIfExists(req.file.filename);
    } catch {
        // Preserve the original request error; cleanup failure is secondary here.
    }
}

// POST /cv/upload
// Uploads the student's first CV file, or appends a new retained CV version.
// QR codes are generated by the participation flow, not by CV upload.
exports.uploadCV = async (req, res) => {
    try {
        const studentId = req.user.id;
        const { cv, version } = await addCvVersion(studentId, req.file);
        const versions = await getCvVersions(cv.id);

        res.json({
            message: "CV version uploaded",
            cv: mapCvResponse(cv, versions),
            version
        });

    } catch (err) {
        await removeUploadedFileOnFailure(req);
        handleControllerError(res, err);
    }
};

// GET /cv/me
// Returns the student's logical CV, latest version, and retained version list.
exports.getMyCV = async (req, res) => {
    try {
        const studentId = req.user.id;
        const cv = await getStudentCv(studentId);

        if (!cv)
            return res.status(404).json({ error: "No CV found" });

        const versions = await getCvVersions(cv.id);

        if (versions.length === 0)
            return res.status(404).json({ error: "No CV versions found" });

        res.json(mapCvResponse(cv, versions));

    } catch (err) {
        handleControllerError(res, err);
    }
};

// PUT /cv
// Appends a new retained version to the student's existing logical CV.
// The participation QR remains stable because it resolves to the latest version.
exports.replaceCV = async (req, res) => {
    try {
        const studentId = req.user.id;
        const existingCv = await getStudentCv(studentId);

        if (!existingCv)
            return res.status(404).json({ error: "No CV to replace" });

        const { cv, version } = await addCvVersion(studentId, req.file);
        const versions = await getCvVersions(cv.id);

        res.json({
            message: "CV version uploaded",
            cv: mapCvResponse(cv, versions),
            version
        });

    } catch (err) {
        await removeUploadedFileOnFailure(req);
        handleControllerError(res, err);
    }
};

// DELETE /cv
// Deletes the student's logical CV and retained files unless it is selected by
// an open participation. Closed participations are detached first so historical
// event records remain without keeping a hard dependency on the CV.
exports.deleteCV = async (req, res) => {
    const connection = await pool.getConnection();

    try {
        const studentId = req.user.id;
        const cv = await getStudentCv(studentId, connection);

        if (!cv)
            return res.status(404).json({ error: "No CV found" });

        await assertCvNotUsedByOpenParticipation(cv.id, connection);

        const latestVersion = await getLatestCvVersion(cv.id, connection);
        const versions = await getCvVersions(cv.id, connection);

        await connection.beginTransaction();

        await connection.query(
            `UPDATE participations
             JOIN events ON events.id = participations.event_id
             SET participations.selected_cv_id = NULL
             WHERE participations.selected_cv_id = ?
             AND NOT (
                events.status = 'open'
                AND events.closed_at IS NULL
             )`,
            [cv.id]
        );

        await connection.query(
            "DELETE FROM cvs WHERE id = ? AND student_id = ?",
            [cv.id, studentId]
        );

        await connection.commit();

        for (const version of versions) {
            await deleteFileIfExists(version.file_path);
        }

        res.json({
            message: "CV deleted",
            deleted_latest_version: latestVersion || null
        });

    } catch (err) {
        await connection.rollback();
        handleControllerError(res, err);
    } finally {
        connection.release();
    }
};
