services:
  db:
    image: mysql:8.0
    container_name: cvqr-db
    environment:
      MYSQL_ROOT_PASSWORD: cvqr
      MYSQL_DATABASE: cvqr
    ports:
      - "3307:3306"
    volumes:
      - cvqr_db_data:/var/lib/mysql
      - ./backend/config/schema.sql:/docker-entrypoint-initdb.d/schema.sql

volumes:
  cvqr_db_data:
